
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gieuqalvgvfbdcjbuvnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpZXVxYWx2Z3ZmYmRjamJ1dm5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxODc3MTIsImV4cCI6MjA1Nzc2MzcxMn0.r-NEYoiLrKayWLXNvRZIeOzF5_Oub-0b28e_gMCYs_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
